version: 2

# This tells GoReleaser NOT to look for a main function
builds:
  - skip: true

release:
  github:
    owner: Freekiehsoes
    name: gripp

changelog:
  sort: asc
  filters:
    exclude:
      - '^reference:'